# tests make
CC = gcc
CCFLAGS = -Wall -g3


BDIR = bin
SRCDIR = src
TSTSDIR = tests
TSTS = $(wildcard $(TSTSDIR)/*.c)
IDIR = include
ODIR = build

MatchesTests = MatchesLists_test.o
main:
		@echo "skata"