name: C/C++ CI
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck

name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - name: make tests
      run: make tests
